## ROI.plugin.cplex: status codes
## Description: provides canonicalization of solver status codes

## STATUS CODES
.add_cplex_status_codes <- function( ) {

  ## CPLEX status codes
  ## from CPLEX 11 reference manual
  ## (see e.e., http://www.decf.berkeley.edu/help/apps/ampl/cplex-doc/refcallablelibrary/index.html)
  ## FIXME: only a (relevant) subset from CPLEX status codes

  ## generic status codes
  add_status_code_to_db("cplex",
                        1L,
                        "CPX_STAT_OPTIMAL",
                        "(Simplex or barrier): optimal solution.",
                        0L
                        )
  add_status_code_to_db("cplex",
                        2L,
                        "CPX_STAT_UNBOUNDED",
                        "(Simplex or Barrier): Problem is unbounded."
                        )
  add_status_code_to_db("cplex",
                        3L,
                        "CPX_STAT_INFEASIBLE",
                        "(Simplex or Barrier): Problem has been proven infeasible."
                        )
  add_status_code_to_db("cplex",
                        4L,
                        "CPX_STAT_INForUNBD",
                        "(Simplex or Barrier): Problem has been proven either infeasible or unbounded."
                        )
  add_status_code_to_db("cplex",
                        5L,
                        "CPX_STAT_OPTIMAL_INFEAS",
                        "(Simplex or Barrier) Optimal solution is available, but with infeasibilities after unscaling"
                        )
  add_status_code_to_db("cplex",
                        11L,
                        "CPX_STAT_ABORT_TIME_LIM",
                        "(Simplex or Barrier): Stopped due to a time limit."
                        )
  ## MIP status codes
  add_status_code_to_db("cplex",
                        101L,
                        "CPXMIP_OPTIMAL",
                        "(MIP): optimal integer solution.",
                        0L
                        )
  add_status_code_to_db("cplex",
                        102L,
                        "CPXMIP_OPTIMAL_TOL",
                        "(MIP): optimal soluton with the tolerance defined by epgap or epagap has been found.",
                        0L
                        )
  add_status_code_to_db("cplex",
                        103L,
                        "CPXMIP_INFEASIBLE",
                        "(MIP): Solution is integer infeasible."
                        )
  add_status_code_to_db("cplex",
                        104L,
                        "CPXMIP_SOL_LIM",
                        "(MIP): The limit on mixed integer solutions has been reached."
                        )
  add_status_code_to_db("cplex",
                        107L,
                        "CPXMIP_TIME_LIM_FEAS",
                        "(MIP): Time limit exceeded, but integer solution exists."
                        )
  add_status_code_to_db("cplex",
                        108L,
                        "CPXMIP_TIME_LIM_INFEAS",
                        "(MIP): Time limit exceeded, no integer solution exists."
                        )
  add_status_code_to_db("cplex",
                        109L,
                        "CPXMIP_FAIL_FEAS",
                        "(MIP): Terminated because of an error, but integer solution exists."
                        )
  add_status_code_to_db("cplex",
                        110L,
                        "CPXMIP_FAIL_INFEAS",
                        "(MIP):Terminated because of an error; no integer solution."
                        )
  add_status_code_to_db("cplex",
                        113L,
                        "CPXMIP_ABORT_FEAS",
                        "(MIP): Stopped, but an integer solution exists."
                        )
  add_status_code_to_db("cplex",
                        114L,
                        "CPXMIP_ABORT_INFEAS",
                        "(MIP): Stopped, no integer solution found."
                        )
  add_status_code_to_db("cplex",
                        115L,
                        "CPXMIP_OPTIMAL_INFEAS",
                        "(MIP): Problem is optimal with unscaled infeasibilities"
                        )
  add_status_code_to_db("cplex",
                        118L,
                        "CPXMIP_UNBOUNDED",
                        "(MIP): Problem is unbounded."
                        )
  add_status_code_to_db("cplex",
                        128L,
                        "CPXMIP_POPULATESOL_LIM",
                        "(MIP MultSols): The limit on optimal mixed integer solutions generated by populate has been reached.",
                        0L
                        )
  add_status_code_to_db("cplex",
                        129L,
                        "CPXMIP_OPTIMAL_POPULATED",
                        "(MIP-MultSols): Populate has completed the enumeration of all solutions it could enumerate.",
                        0L
                        )
  add_status_code_to_db("cplex",
                        130L,
                        "CPXMIP_OPTIMAL_POPULATED_TOL",
                        "(MIP-MultSols): similar to 129L but additionally objective value fits the tolerance specified by paramaters.",
                        0L
                        )
  invisible(TRUE)
}

